Setup webpack
badimalex/react-backend-example pull request #2
Opened 2017-01-07 21:25 UTC by badimalex

Remove express

2017-01-08 16:46 UTC, badimalex commented
прикрутил https://reactstrap.github.io/, что получилось
![image](https://cloud.githubusercontent.com/assets/4666600/21751607/3082cbe4-d5ca-11e6-8363-302de23bf7b4.png)

2017-01-14 09:22 UTC, index01d requested changes
Если запустить ./node_modules/eslint/bin/eslint.js . , то линтер имеет много, что сказать:) Это было бы неплохо исправить; также в консоли есть предупреждение от moment.js.

2017-01-14 09:22 UTC, index01d commented on index.html
> +  <script src="dist/bundle.js" charset="utf-8"></script>
Здесь уже должен быть assets/bundle.js ; dist использовался при статической сборке и его можно удалить

2017-01-26 17:09 UTC, index01d approved these changes
Рекомендую разделять по директориям элементы и виджеты (BlogItem+BlogList/PieChart+Like+Image), в остальном все хорошо.

2017-01-26 17:16 UTC, merged