Lesson 5
badimalex/react-backend-example pull request #3
Opened 2017-01-27 06:31 UTC by badimalex

2017-01-30 17:31 UTC, badimalex commented
сменил бутстрап на semantic-ui, чтобы идти в ногу по ходу курса.

2017-01-31 07:58 UTC, index01d commented
:)) продавил семантик. а кнопка like так и осталась бутстрейповой

2017-01-31 07:58 UTC, index01d approved these changes

2017-02-13 07:48 UTC, index01d requested changes

2017-02-13 07:48 UTC, index01d commented on src/components/widgets/Pagination.js
> +    this.state = this.props;
так делать нельзя (см. урок по состоянию),  состояние не должно считаться только из свойств. В данном случае состояние попросту не нужно и можно пользоваться только свойствами.

2017-02-13 12:05 UTC, index01d commented
в целом можно было бы тогда компонент оформить как stateless, но ок, прув

2017-02-13 12:05 UTC, index01d approved these changes

2017-02-13 12:12 UTC, merged