Redux added
badimalex/react-backend-example pull request #4
Opened 2017-02-15 00:38 UTC by badimalex

2017-02-17 20:06 UTC, badimalex commented
просьба обратить внимание на файл src/actions/Posts.js и сказать все ли в нем верно.

2017-02-22 12:11 UTC, index01d requested changes

2017-02-22 12:11 UTC, index01d commented on src/components/containers/BlogPage.js
>    getChartData() {
должно теперь происходить в контейнере

2017-02-22 12:11 UTC, index01d commented on src/components/containers/BlogPage.js
> +      searchRequest(phrase);
не лучшее решение, когда нужно сформировать ссылку с поисковым запросом. в таком случае лучше сделать history.push. Хотя все зависит от постановки задачи. В любом случае не криминал.

2017-02-22 12:11 UTC, index01d commented on src/components/containers/BlogPage.js
> +    const { fetchPosts } = this.props.actions;
чувствуется некоторая избыточность этого метода,  если бы таковых не было то компонент стал бы stateless

2017-02-23 08:06 UTC, index01d approved these changes

2017-02-23 08:06 UTC, index01d commented
в Posts если что смотрел, криминала не нашел

2017-02-23 09:38 UTC, merged