Lesson 9
badimalex/react-backend-example pull request #8
Opened 2017-04-11 22:48 UTC by badimalex

2017-04-18 17:52 UTC, index01d requested changes

2017-04-18 17:52 UTC, index01d commented on src/components/containers/Edit.js
> +    switch (type) {
лучше декомпозировать на отдельные компоненты и передавать в виде children

2017-04-18 17:52 UTC, index01d commented on src/components/containers/Edit.js
> +              input.onChange(moment(date).format('YYYY-MM-DD HH:mm:ss'));
отсюда полагаю лучше выделить хелпер для форматирования даты

2017-04-18 17:52 UTC, index01d commented on src/components/containers/Edit.js
> +          initialDate={input.value ? moment(input.value) : null}
тогда здесь не придется делать условную логику (см ниже)

2017-04-18 17:52 UTC, index01d commented on src/components/ui/BlogItem.js
> +        <Link to={editPostPath(id)} >
лучше в контейнерном компоненте пробежать по постам и приготовить урлы, тогда презентационный компонент не узнает про роутерные хелперы и роутерную логику

2017-04-19 18:17 UTC, badimalex commented on src/components/ui/BlogItem.js
> +        <Link to={editPostPath(id)} >
может в редьюсере? а если этот компонент в нескольких используется? может так оставим?

2017-04-20 07:20 UTC, index01d requested changes
Теперь образовалось дублирование кода. Можно выделить компонент Field и использовать во всех реализациях конкретных компонентов ввода.

2017-04-20 07:20 UTC, index01d commented on src/components/containers/Edit.js
> +import TextareaField from '../ui/form/TextareaField';
нужно использовать абсолютные пути

2017-04-20 07:21 UTC, index01d commented on src/components/ui/BlogItem.js
> +        <Link to={editPostPath(id)} >
если оставить тут, то когда будешь использовать например storybook тебе придется затащить в сторибук роутерную логику. Желательно чтобы презентационные компоненты не зависели ни от redux-стора, ни от роутера

2017-04-21 04:56 UTC, index01d approved these changes

2017-05-08 09:56 UTC, index01d requested changes

2017-05-08 09:56 UTC, index01d commented on src/components/containers/Edit.js
> +import React from 'react';
лучше вынести из контейнера презентационную часть формы

2017-05-08 09:56 UTC, index01d commented on src/components/ui/CommentForm.js
> +  handleSubmit(values) {
содержимое этой функции

2017-05-08 09:56 UTC, index01d commented on src/components/ui/CommentForm.js
> +  enableReinitialize: true,
должно быть здесь под ключом `onSubmit: (values, dispatch, props) => ...`

2017-05-08 09:56 UTC, index01d commented on src/components/ui/CommentForm.js
> +  enableReinitialize: true,
при этом нужно разделить презентационный компонент формы и контейнер

2017-05-08 09:56 UTC, index01d commented on src/components/ui/CommentForm.js
> +          onSubmit={handleSubmit((values) => this.handleSubmit(values))}
здесь нужно оставить просто `onSubmit={handleSubmit}`

2017-05-11 04:55 UTC, index01d approved these changes

2017-05-11 04:55 UTC, index01d commented on src/containers/PostEditContainer.js
> +  initialValues: state.post.entry && {
будь готов к возможному отсутствию ключей, используй get из lodash, бро

2017-05-11 06:16 UTC, merged